### ISSUE TITLE
Expose `octokit.addRoutes` to dynamically add new routes

### ISSUE THREAD

**Issue by bkeepers** [gr2m/octokit-rest-plugin-example#1]
From the README:

> If there are many new endpoints it could be worth to create a [`routes.json file like @octokit/rest/lib/routes.json`](https://github.com/octokit/rest.js/blob/master/lib/routes.json) and then build the endpoints based on that file like the core [endpoint-methods plugin](https://github.com/octokit/rest.js/tree/master/lib/plugins/endpoint-methods).

For APIs that are still in private beta, it would be awesome to have a way to add more routes in the same format as the existing `routes.json` file.

For example, imagine a plugin that looks like this:

```js
module.exports = function privateBetaFeature(octokit) {
  octokit.addRoutes(require('./private-beta-feature'))
}
```

cc @gr2m

**Comment by gr2m** [comment]
I'll make a separate plugin for it, for now

**Comment by gr2m** [comment]
there you go https://github.com/gr2m/octokit-rest-plugin-add-endpoints

something is funky with travis, github or npm so the release didn't work, but the code should be good. I'll try to release it again later tonight

**Comment by gr2m** [comment]
alright, published now: https://www.npmjs.com/package/octokit-rest-plugin-add-endpoints
